### ISSUE TITLE
打开google和GitHub等外网，基本上都要等到一两秒甚至三秒

### ISSUE THREAD

**Issue by Lovefish** [MoGuangYu/Surfing#10]
换了两个ping都很低的机场，都是一样的情况。访问国内的站点倒是都是很正常打开。

**Comment by developor** [comment]
附議

**Comment by developor** [comment]
> 换了两个ping都很低的机场，都是一样的情况。访问国内的站点倒是都是很正常打开。

附議

**Comment by developor** [comment]
> > 關掉區域網路和嗅探就會好一些
> 
> 可以指出具体是哪里吗？

![Uploading Screenshot_2023-12-07-22-46-43-008_com.android.chrome-edit.jpg…]()

**Comment by Lovefish** [comment]
> > > 關掉區域網路和嗅探就會好一些
> > 
> > 
> > 可以指出具体是哪里吗？
> 
> ![Screenshot_2023-12-07-22-46-43-008_com android ch](https://private-user-images.githubusercontent.com/67617330/288796754-2c190f99-dc7d-4324-9112-8033d1d1e3fb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NzYwMTksIm5iZiI6MTcwMTk3NTcxOSwicGF0aCI6Ii82NzYxNzMzMC8yODg3OTY3NTQtMmMxOTBmOTktZGM3ZC00MzI0LTkxMTItODAzM2QxZDFlM2ZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDE5MDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZjIwNzQ0MTc2NTA2ZTMzZDM5NjI2NjRiMjY3MzBmYzg3ZGU5YTU0ZWM3ZjcwZDVkNzcyYzE5YTIwZmMwMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.raCebfQQBRRpxa4V11DuCLl6VhA2jmA1qPJWy-MeEVY)

感觉没什么用。。。

**Comment by developor** [comment]
註釋掉 fallback 果然有效

**Comment by Lovefish** [comment]
> 註釋掉 fallback 果然有效

细说

**Comment by developor** [comment]
> > 註釋掉 fallback 果然有效
> 
> 细说

![Screenshot_2023-12-24-20-46-52-539_bin mt plus-edit](https://github.com/MoGuangYu/Surfing/assets/67617330/d984161b-fdda-4c7a-b0f6-2152c4d23c41)

**Comment by Lovefish** [comment]
> > > 註釋掉 fallback 果然有效
> > 
> > 
> > 细说
> 
> ![Screenshot_2023-12-24-20-46-52-539_bin mt plus-edit](https://private-user-images.githubusercontent.com/67617330/292671185-d984161b-fdda-4c7a-b0f6-2152c4d23c41.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzYxMjMsIm5iZiI6MTcwMzQzNTgyMywicGF0aCI6Ii82NzYxNzMzMC8yOTI2NzExODUtZDk4NDE2MWItZmRkYS00YzdhLWIwZjYtMjE1MmM0ZDIzYzQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE2MzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYzU1NGU4ZTRhMGMzOTRlN2I1Njk0ZDM1YzQ1NDAwNTkyMWEwMmNjNDUyOWVlYzdlYzNiNmZhYTllYWFmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y6Mb8WcF3Nh-E9H-HsU4lq_LczQsBBfr1ogvDGWzwp4)

初步观察来看，好像是有改善😯
