### ISSUE TITLE
请问如何代理私有网段地址

### ISSUE THREAD

**Issue by Shattered217** [MoGuangYu/Surfing#33]
本人在家中部署了vm节点，用于代理流量回家，但是配置规则后仍然无法访问内网ip地址（在别的客户端测试过皆可正常访问）

**Comment by Shattered217** [comment]
好的，经过尝试，在tun mixed模式下似乎是解决了这个问题

**Comment by itcbx** [comment]
tproxy模式为了防止回环，防火墙有设置绕过私有地址，私有地址不会在由clash处理
