### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by lzlq** [MoGuangYu/Surfing#40]
默认规则个别国内APP打不开，设置黑白名单都不行

**Comment by lzlq** [comment]
> 默认规则个别国内APP打不开，设置黑白名单都不行

**Comment by RyanRaw** [comment]
规则又不是万能的，改成全局，麻烦先看下别的iisue

**Comment by lzlq** [comment]
感谢回复，只是想越懒越好😂












劉旭
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月1日(周六) 上午7:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [MoGuangYu/Surfing] 一个小问题 (Issue #40)




 
规则又不是万能的，改成全局，麻烦先看下别的iisue
