### ISSUE TITLE
为啥打和平精英的时候，底下会出现黄色断开链接的标识，虽然延迟显示正常，但还是感觉到很卡

### ISSUE THREAD

**Issue by litocc** [MoGuangYu/Surfing#57]
![5a23e8c09cb27ab10d6313d07262a54c](https://github.com/MoGuangYu/Surfing/assets/68491603/d8c59a8f-650d-448d-8a0e-58c0655aa529)

如上图所示，打游戏时出现黄色断开链接，延迟显示正常，但会卡顿，但是配置里我加了规则：
  - PROCESS-NAME,com.tencent.tmgp.pubgmhd,DIRECT

国内的分流也是正常的，看链接日志也是显示com.tencent.tmgp.pubgmhd这个进程走的直连，但就是会卡顿

**Comment by hanboyi** [comment]
大哥，麻烦问一下这个问题解决了吗，我也出现这个问题了
