### ISSUE TITLE
changelog里面说应用分流规则，是在哪里能够修改呢？

### ISSUE THREAD

**Issue by Lovefish** [MoGuangYu/Surfing#6]
应用分流增加中国抖音

部分应用分流规则调整为本机进程匹配，为以下应用
网易音乐
国际抖音
中国抖音

以上的更新描述，是排除特定的应用吗？在配置里的应用黑白名单也没有设置，是不管设置没设置都会排除吗？

**Comment by MoGuangYu** [comment]
http://127.0.0.1:9090/ui/ 里面可以控制这些应用的流量

**Comment by Lovefish** [comment]
> http://127.0.0.1:9090/ui/ 里面可以控制这些应用的流量

这个我知道，我只是想知道更新里面所提到的应用分流是所谓的分应用代理吗？我设置白名单的配置文件，还需要排除他们吗？
