### ISSUE TITLE
白名单模式下，白名单app正常联网，部分其他app不正常。

### ISSUE THREAD

**Issue by lslxgh** [MoGuangYu/Surfing#79]

**Comment by lslxgh** [comment]
解决了，关了tun就好了。我看很多人白名单使用模式有问题，根据我浅薄的经验，跟大家说一下。
1、必须是redir-host模式。
dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
2、必须把tun关了。
tun:
  enable: false
3、白名单模式，各个应用间有空格。
proxy_mode="whitelist"
# blacklist / whitelist / core
user_packages_list=("0:com.yjllq.internet" "0:org.telegram.messenger.web" "0:com.twitter.android" "0:com.google.android.youtube" "0:com.google.android.gm")

**Comment by Cdh0129** [comment]
感谢

**Comment by dangerboy1986** [comment]
redir-host是不是没有fake-ip安全？
另外，最近的更新在WIFI下关闭tun有bug
